### ISSUE TITLE
Possible to add option to not minimize end credits?

### ISSUE THREAD

**Issue by cloudgreen** [jonluca/Never-Ending-Netflix#13]
Great extension!

Would it be possible to add an option to make Netflix NOT minimize the end credits? It would be awesome! :-)

**Comment by jonluca** [comment]
Thanks!

What do you mean not minimize the end credits? Like on series finales, when there are no more episodes left?

**Comment by cloudgreen** [comment]
Well, when watching Netflix in a browser on a computer, it will minimize the end credits to a small thumbnail and show a big screen that urges you to move on to the next episode. (This does not happen on the Netflix app on iPhone though.)

There was a Chrome app (from Lifehacker, I think) that could modify Netflix into just showing the credits as usual, but the app is not maintained anymore and it stopped working a long time ago.

![Netflix end credits](https://user-images.githubusercontent.com/42112877/64565984-3b2d0d80-d355-11e9-8dcc-32d47fa4231d.png)

Any possibility of integrating such a feature into your nice Netflix app? :)

**Comment by jonluca** [comment]
This should be possible - I'll look into it over the weekend.

**Comment by jonluca** [comment]
I've implemented this feature in v2.7. I'd also recommend moving to Netflix Extended as it's a better extension, IMO, and I don't really active develop this one that much https://chrome.google.com/webstore/detail/netflix-extended/gjcgfkhgpaccjpjokgpekpgpphgaanej

**Comment by cloudgreen** [comment]
Thanks for getting back! :) It's been a couple of years and I'm mainly watching Netflix via other means nowadays, but Netflix Extended looks great! Keep up the great work! 👍
