### ISSUE TITLE
Last netflix player update: "Still watching" dialog appears again.

### ISSUE THREAD

**Issue by jsantosr** [jonluca/Never-Ending-Netflix#14]
Add this to line 151 NEN.js on function enableSkipStillHere
`  selectors.push(".nf-flat-button-icon-play");`

Thank you

**Comment by jonluca** [comment]
Thanks for the report! It's a *little* more complicated than that as it seems they changed the way they deal with events (maybe they transitioned to react hooks with a new library?

Regardless I think I fixed it - https://github.com/jonluca/Never-Ending-Netflix/commit/1d51cd4f7baf5291b712acf3759204dd03becad4 that is version 2.5, which has been sent to the webstore and should be up soon. Let me know if it works for you.

**Comment by jsantosr** [comment]
Perfect. I saw that the class I mentioned is used in more places and became more complex and I came to report it but I saw that you had worked on it.

It works perfect. Thank you
