### ISSUE TITLE
Not Working With New Netflix UI

### ISSUE THREAD

**Issue by hb-i** [jonluca/Never-Ending-Netflix#16]
Netflix did some tweaking to their design this week and now skip intro isnt working.

**Comment by mgssf** [comment]
Continue playing isn't working either.

**Comment by mgssf** [comment]
I just submitted a pull request that fixes the "Continue Watching" button on new Netflix UI

**Comment by jonluca** [comment]
I've implemented this feature in v2.7. I'd also recommend moving to Netflix Extended as it's a better extension, IMO, and I don't really active develop this one that much https://chrome.google.com/webstore/detail/netflix-extended/gjcgfkhgpaccjpjokgpekpgpphgaanej
