### ISSUE TITLE
[Request] Auto Watch Credit

### ISSUE THREAD

**Issue by atamsffl** [jonluca/Never-Ending-Netflix#5]
Can you add a feature to auto click "watch credits"? Thanks!

**Comment by jonluca** [comment]
Could you send an example of a show or movie that has this? It should be fairly easy to add.

**Comment by atamsffl** [comment]
BoJack Horseman S1E1, credits start at about 24:15.

**Comment by jonluca** [comment]
Sounds good, I'll work on it later tonight!

**Comment by jonluca** [comment]
Update is pushed, should be live in the next couple hours. Let me know if it works for you!
